### ISSUE TITLE
这个要选对时间区否则签到失败

### ISSUE THREAD

**Issue by fhqswcan** [njzjz/ithome-auto#19]
这个要选对时间区否则签到失败

**Comment by njzjz** [comment]
已修复。除了`export TZ=Asia/Shanghai`以外，顺便解决了https://github.com/daimiaopeng/IthomeQianDao/issues/8，从daimiaopeng/IthomeQianDao更新了代码。

另外我发现虽然提示签到失败，但其实签成功了的。
